# Generated by Django 2.0 on 2018-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='data',
        ),
        migrations.AddField(
            model_name='eventos',
            name='ano',
            field=models.CharField(default=37, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='dia',
            field=models.CharField(default=23, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='horario',
            field=models.CharField(default=25, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='mes',
            field=models.CharField(default=67, max_length=2),
            preserve_default=False,
        ),
    ]
