# Generated by Django 2.0 on 2018-01-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180111_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='endereco',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
