# Generated by Django 2.0 on 2018-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
