# Generated by Django 2.0 on 2018-01-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180124_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horario',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
