# Generated by Django 2.0 on 2018-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horario',
            field=models.CharField(max_length=5),
        ),
    ]
