# Generated by Django 2.0 on 2018-01-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180124_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
