# Generated by Django 2.0 on 2018-01-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180124_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horario',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
