# Generated by Django 2.0 on 2018-01-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180125_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/'),
        ),
    ]
