# Generated by Django 2.0 on 2018-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180125_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/'),
        ),
    ]
