# Generated by Django 2.0 on 2018-01-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180125_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.FileField(upload_to='core/static/img'),
        ),
    ]
