# Generated by Django 2.0 on 2018-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180125_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.FileField(upload_to=''),
        ),
    ]
