# Generated by Django 2.0 on 2018-01-25 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180125_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, message='Horário no formato 00,00')]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
