# Generated by Django 2.0 on 2018-01-25 23:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(5, message='Horário no formato 00,00')]),
        ),
    ]
